### ISSUE TITLE
MibLoader not working in multi threaded environments

### ISSUE THREAD

**Issue by maspholm** [cederberg/mibble#21]
The MibLoader.MibSource class uses a static reference to the ASN.1 parser:

```
private static class MibSource {
    private static Asn1Parser parser = null;
```

This means that two threads using the MibLoader simultaneously will use the same stateful parser object with the result that both parsings fail with unpredictive results.

Some ways to fix the issue:
- Make the parser variable class level
- Make the parser variable thread local
- Make the access API synchronized to guarantee single threaded access

**Comment by cederberg** [comment]
There are more reasons than this for not loading MIB files in parallell from several threads. In fact, the javadoc even says so:

> The MIB loader is not thread-safe, i.e. it cannot be used concurrently in multiple threads.

See https://www.mibble.org/doc/release/api/net/percederberg/mibble/MibLoader.html

I strongly recommend synchronizing all access to the MibLoader if possible.

**Comment by maspholm** [comment]
Being not-thread safe is one thing. Using static stateful objects so that not even two different MibLoader objects can operate in parallell is another. Using a static parser would perhaps make sense if the MibLoader was a singleton object, but it is not. It's not possible to tell from the API that you cannot even have two different MibLoader objects and use them from different threads.

The way I worked around the problem was to use a Proxy object that uses synchronization on a singleton monitor object for all load-methods. This feels like something that should be handled by the library instead of the application code.

**Comment by cederberg** [comment]
Ah, I see. This is a bug, separate MibLoader instances should of course be possible to use in parallell (if needed for some reason). The `parser` variable should obviously be an instance variable for the loader itself.

**Comment by cederberg** [comment]
This is now fixed on the master branch. Thanks for reporting this!
