### ISSUE TITLE
Overriding hashtable entries - Bug?

### ISSUE THREAD

**Issue by peske** [cederberg/mibble#22]
First - great work!
Second - I'm going through code thinking about porting it to .NET Core. If I decide to do so - I'll contact you about licensing related stuff...
Question:
I've noted that in line https://github.com/cederberg/mibble/blob/master/src/java/net/percederberg/mibble/Mib.java#L184 old value can be overridden (multiple `MibValueSymbol` instances can have the same value).
Is it _expected behavior_ or it is a bug?

Thanks!

**Comment by cederberg** [comment]
Hmm. Yes, I guess it is possible to create MIB file that causes this behaviour. Haven't ever seen one though. Could be a good old warning here though. Especially since the code is inside the `validate()` method...

**Comment by cederberg** [comment]
Warnings now added to master branch (upcoming 2.10 release). Thank!
