### ISSUE TITLE
Add support for AES Privacy

### ISSUE THREAD

**Issue by thomric2** [cederberg/mibble#24]
Please add support for AES Privacy mode. This is currently an option for the linux snmpcmd -x argument.

**Comment by cederberg** [comment]
Seems I've missed upgrading Westhawk SNMP to version 6.1 where AES is included. So I guess that should be done first.

**Comment by cederberg** [comment]
Fixed in 2.10.1.

**Comment by thomric2** [comment]
Thanks!
