### ISSUE TITLE
 I test parsing mib file error

### ISSUE THREAD

**Issue by YuanFY** [cederberg/mibble#31]
Download source code for testing, analysis of a mib file the following error:
net.percederberg.mibble.MibLoaderException: found 232 MIB loader errors
	at net.percederberg.mibble.MibLoader.loadQueue(MibLoader.java:796)
	at net.percederberg.mibble.MibLoader.load(MibLoader.java:602)
	at net.percederberg.mibble.MibLoader.load(MibLoader.java:529)
	at TestMain.test(TestMain.java:32)
	at TestMain.main(TestMain.java:21)

Then I print a specific error similar to the following error
undefined symbol 'experimental'
referenced value is not an object identifier
undefined symbol 'DisplayString'

But these keywords, such as experimental, TimeTicks, DisplayString have been imported, why this error can not find it?

**Comment by YuanFY** [comment]
The MIB file for the test is here: https://github.com/YuanFY/blog_demo/tree/master/src/test/FCMGMT-MIB-40.mib

**Comment by YuanFY** [comment]
I know the reason.  Thank you !

**Comment by Muthu-datasirpi** [comment]
> I know the reason. Thank you !

kindly explain the reason for this issue
