### ISSUE TITLE
Pass target IP address on command line?

### ISSUE THREAD

**Issue by richb-hanover** [cederberg/mibble#41]
I am successfully launching MibbleBrowser from the command line with:

`java -jar ~/github/mibble-2.10.1/MibbleBrowser.jar`

It would be useful to pass along the IP address of a target as an argument in the command line. (I would like the MibbleBrowser window to display information about that device instead of the default 127.0.0.1) Is this possible? Thanks!

**Comment by cederberg** [comment]
It isn't possible at the moment, but I guess that MibbleBrowser could be improved to support this.

But perhaps it would be enough to simply restore the IP address and SNMP settings (except passwords perhaps) from the previous run? Similar to how the open files are restored if none are specified on the command-line?

**Comment by richb-hanover** [comment]
Thanks for the speedy response. I would use this ability to allow Intermapper to launch the MibbleBrowser to display information about a selected device. That's the use case for passing the IP address as an argument on the command line... 

But you're right - if Mibble handles the device address, there will be pressure to handle credentials, etc. Probably not worth it, as this was just a passing experiment for me.

PS I was with Dartware years ago, and always appreciated Mibble and the work you did to preserve files across launches. I hope you're well.
