### ISSUE TITLE
Error: Could not find or load main class

### ISSUE THREAD

**Issue by AKEIng** [cederberg/mibble#43]
I downloaded the source code directly and executed MibbleBrowser.bat, but it gives an "Error: Could not find or load main class" error. I tried modifying the bat file and successfully executed the MibbleBrowser class, but it still throws an error. I'm not sure if I missed any steps or if it's a bug in the original code.

**Comment by cederberg** [comment]
Have you tried to download the [mibble-2.10.1.tar.gz](https://github.com/cederberg/mibble/releases/download/v2.10.1/mibble-2.10.1.tar.gz) release build? If you have Java installed, it should be enough to double-click the `MibbleBrowser.jar` file at the root.
