### ISSUE TITLE
MibbleBrowser doesn't display SNMPv1 traps

### ISSUE THREAD

**Issue by cederberg** [cederberg/mibble#6]
The SNMPv1 TRAP-TYPE values are normally not part of the OID tree. So they are not displayed in the MibbleBrowser, since it operates on the OID tree only.

**Comment by cederberg** [comment]
Fixed in 2.10.

**Comment by yonghaoy** [comment]
Hi Per
When 2.10 will be released? I have some trouble to transform SNMPv1's type. We append enterprise.0.specificTrap, but it won't be transformed successfully. 
Does this bug fix my issue? Thanks!

**Comment by cederberg** [comment]
I've just uploaded 2.10.beta1 to the release page: https://github.com/cederberg/mibble/releases

Please give it a try and let me know if it doesn't solve your issue. A final 2.10 version should be out in about a week if no bugs are found.

**Comment by yonghaoy** [comment]
thanks Per!
